#!/usr/bin/env bash
# This script trasfers a file from my client to server

if [ $# -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" "$1" "$3@$2":~/
fi
