#!/usr/bin/env bash
# this script adheres to the following requirements:
# 1- Installs nginx on my web-01 server
# 2- Assures nginx listens on port 80
# 3- When querying nginx at its root `/` with a GET request (requesting a page) using curl, it must return a page that contains the string `Hello World!`

sudo apt update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.ubuntu-debian.html
sudo service nginx start
