#!/usr/bin/env bash
# this script adheres to the following requirements:
# 1- Installs nginx on my web-01 server
# 2- Assures nginx listens on port 80
# 3- When querying nginx at its root `/` with a GET request (requesting a page) using curl, it must return a page that contains the string `Hello World!`
# 4- Redirects the user when they hit /redirect_me after the domain name or IP address of the server web-01

sudo apt update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i -e "|listen 80 default_server;|a/location /redirect-me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}" /etc/nginx/sites-enabled/default
sudo service nginx start
