#!/usr/bin/env bash
# Configures Nginx to include a response header with the name X-Served-by and the value [STUDET-ID]-web01 or [STUDENT-ID]-web02 (depending on the server static host name) in the http response i web-01 and web-02.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i "/listen 80 default_server/a\ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i "/listen 80 default_server/a\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _;/a \\\n\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-enabled/default
sudo service nginx reload
