#!/usr/bin/env bash
# This Bash script pings an IP address passed as an argument.
# Requirements:
# -Accepts a string as an argument
# -Displays `Usage: 5-is_the_host_on_the_network {IP_ADDRESS}`
# -Ping the IP 5 times
if (($# != 1));
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
if [ -n $1 ];
then
	ping -c 5 $1
fi
