#!/usr/bin/env bash
# This script i displaying "Best School" 10 times
# but for the 4th iteration, displays `bad luck` 
# for the 8th iteration, displays `good luck`
# then `Best School` for other iterations.
i=1
while ((i<=10));
do
    if ((i == 4));
    then
        echo "bad luck"
    elif ((i == 8));
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done
