#!/usr/bin/env bash
# This script i displaying "Best School" 20 times
# but for the 4th iteration, displays `bad luck for China` 
# for the 9th iteration, displays `bad luck for Japan`
# for the 17th iteration, displays `bad luck for italy`
# for the `Best School` for other iterations.
i=1
while ((i<=20));
do
	echo $i
	case $i in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
	esac
		i=$((i + 1))
		done
