#!/usr/bin/env bash
# This is a Bash script that displays the time 12 hours and 59 minutes
# display hours from 0 to 12
# displays minutes from 1 to 59
HOURS=0
while ((HOURS <= 12));
do
	echo "Hour: $HOURS"
	MINUTES=1
	while ((MINUTES <= 59));
	do
		echo "$MINUTES"
		((MINUTES++))
	done
	((HOURS++))
done
