#!/usr/bin/env bash
# This bash script displays the content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

list=$(ls)
for filename in $list;
do
	echo "$filename" | cut -d '-' -f 2
done
