#!/usr/bin/env bash
# Setup a firewall that blocks all incoming traffic except the following TCP ports 22, 443 and 80

sudo apt update
sudo apt install ufw

sudo ufw allow 22
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
